### Sign In
POST http://localhost:5215/api/authentication/sign-in
Api-Version: 1
Content-Type: application/json

{
  "email": "admin@riskscreening.com",
  "password": "Admin123!"
}

###

### Get Current User
GET http://localhost:5215/api/authentication/me
Api-Version: 1
Authorization: Bearer {{token}}

###
